version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    volumes:
      #- ./public:/var/www/html/public
      - ./router.php:/var/www/html/router.php
      - ./app:/var/www/html/app
      - ./apache/vhost.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=yourpetUser
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=yourpet

  db:
    image: mysql:8.4  # use a specific version of MySQL, adjust as necessary
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: yourpet
      MYSQL_USER: yourpetUser
      MYSQL_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/mysql
      - ./setup/yourpet.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
