version: '3.8'

services:
  yourpet-web:
    build:
      context: .
    ports:
      - "8082:80"
    volumes:
      - ./public:/var/www/html/public
      - ./app:/var/www/html/app
      - ./apache/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./composer.json:/var/www/html/composer.json
    depends_on:
      - yourpet-db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - RESEND_API_KEY=${RESEND_API_KEY}

  yourpet-db:
    image: mysql:8.4  # use a specific version of MySQL, adjust as necessary
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./setup/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 8083:80
    depends_on:
      - yourpet-db
      

volumes:
  db_data:
